name: Build Joypadmapper APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du dépôt
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      # 2️⃣ Installer Java 8 (compatibilité projets Android anciens)
      - name: Installer Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      # 3️⃣ Mise en cache des dépendances Gradle
      - name: Mettre en cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-

      # 4️⃣ Rendre gradlew exécutable
      - name: Rendre gradlew exécutable
        run: chmod +x ./gradlew

      # 5️⃣ Compiler l’APK debug
      - name: Compiler l’APK Debug
        run: ./gradlew assembleDebug

      # 6️⃣ Sauvegarder l’APK
      - name: Sauvegarder l’APK
        uses: actions/upload-artifact@v4
        with:
          name: joypadmapper-apk
          path: app/build/outputs/apk/debug/app-debug.apk
